enum TradeActions {
  SET_TEAMS = 'SET_TEAMS',
  SET_TEAM_SELECT_OPTIONS = 'SET_TEAM_SELECT_OPTIONS',
  SET_TRADE_HISTORY = 'SET_TRADE_HISTORY',
  SET_ASYNC_START = 'SET_ASYNC_START',
  SET_ASYNC_SUCCESS = 'SET_ASYNC_SUCCESS',
  SET_ASYNC_ERROR = 'SET_ASYNC_ERROR',
  SET_QUERY_PARAMS = 'SET_QUERY_PARAMS'
}

enum SettingsActions {
  SET_ASYNC_START = 'SET_ASYNC_START',
  SET_ASYNC_SUCCESS = 'SET_ASYNC_SUCCESS',
  SET_ASYNC_ERROR = 'SET_ASYNC_ERROR',
  SET_QUERY_PARAMS = 'SET_QUERY_PARAMS'
}

enum PlayerActions {
  SET_PLAYER = 'SET_PLAYER'
}

export { TradeActions, SettingsActions, PlayerActions };
