enum Actions {
  SET_TEAMS = 'SET_TEAMS',
  SET_TEAM_SELECT_OPTIONS = 'SET_TEAM_SELECT_OPTIONS',
  SET_TRADE_HISTORY = 'SET_TRADE_HISTORY',
  SET_ASYNC_START = 'SET_ASYNC_START',
  SET_ASYNC_SUCCESS = 'SET_ASYNC_SUCCESS',
  SET_ASYNC_ERROR = 'SET_ASYNC_ERROR'
}

export { Actions };
